[package]
name = "tuple"
version = "0.3.9"
authors = ["Sebastian Köln <sebk@rynx.org>"]
description = "Element-wise operations on tuples"
documentation = "https://docs.rs/tuple"
homepage = "https://github.com/s3bk/tuple"
repository = "https://github.com/s3bk/tuple"
keywords = ["tuple", "science"]
license = "MIT"

[features]
default = ["impl_num", "impl_serde"]
impl_num = ["num-traits"]
impl_simd = ["stdsimd"]
impl_serde = ["serde"]
nightly = []

[dependencies]
num-traits = { version = "0.1.*", optional=true }
serde = { version = "1.0.*", optional=true }

[dependencies.stdsimd]
version = "0.0.4"
optional = true
