[package]
name = "tuple"
version = "0.3.0"
authors = ["Sebastian Köln <sebk@rynx.org>"]
description = "Element-wise operations on tuples"
documentation = "https://docs.rs/tuple"
homepage = "https://github.com/s3bk/tuple"
repository = "https://github.com/s3bk/tuple"
keywords = ["tuple", "science"]
license = "MIT"

[features]
default = ["impl_num", "impl_serde"]
impl_num = ["num-traits"]
impl_simd = ["simd"]
impl_serde = ["serde"]

[dependencies]
num-traits = { version = "0.1.*", optional=true }
serde = { version = "1.0.*", optional=true }

[target.'cfg(any(target_arch="x86", target_arch="x86_64"))'.dependencies]
simd = { version = "0.2.*", optional=true }
