[package]
name = "tuple"
version = "0.2.0"
authors = ["Sebastian Köln <sebk@rynx.org>"]
description = "Element-wise operations on tuples"
documentation = "https://docs.rs/tuple"
homepage = "https://github.com/s3bk/tuple"
repository = "https://github.com/s3bk/tuple"
keywords = ["tuple"]
license = "MIT"

[features]
default = ["impl_num"]
impl_num = ["num-traits"]
impl_simd = ["simd"]

[dependencies]
num-traits = { version = "0.1.*", optional=true }

[target.'cfg(any(target_arch="x86", target_arch="x86_64"))'.dependencies]
simd = { version = "0.2.*", optional=true }
