[package]
name = "tuple"
version = "0.1.2"
authors = ["Sebastian Köln <sebk@rynx.org>"]
description = "Element-wise operations on tuples"
documentation = "https://docs.rs/tuple"
homepage = "https://github.com/s3bk/tuple"
repository = "https://github.com/s3bk/tuple"
keywords = ["tuple"]
license = "MIT"

[features]
default = ["impl_num"]
impl_num = ["num-traits"]

[dependencies]
num-traits = { version = "0.1.*", optional=true }
